### ISSUE TITLE
Info Gathering / Stakeholder Meeting with Austin

### ISSUE THREAD

**Issue by rhinnawi** [rhinnawi/main_site#4]
Definition of Done
- Meeting has been completed with Austin, and he has been updated on our plans
- We have his feedback and updates logged from the meeting, as well as potential next steps / action items
- All media content has been received (e.g. images, links, etc.)

**Comment by KeybladeMasterFoster** [comment]
Meeting is planned for 4/25 at night time TBD. Files for site on drive or personal device
